# Executable names:
EXE = flights #we need an executable for our flights file
TEST = test #we also need one for our tests

# Add all object files needed for compiling:
EXE_OBJ = main.o #we'll need main for running flights
OBJS = main.o Airport.o Route.o Graph.o csv_reader.o #these are all of the other files we  need objects of

# Use the cs225 makefile template:
include cs225/make/cs225.mk #make sure we can use the cs225 files

