# Executable names:
EXE = flights
TEST = test

# Add all object files needed for compiling:
EXE_OBJ = main.o
OBJS = main.o Airport.o Route.o Graph.o csv_reader.o

# Use the cs225 makefile template:
include cs225/make/cs225.mk

